name: Train Players

on:
  workflow_dispatch: # Allows you to manually click a button to run it

jobs:
  train:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium
          
      - name: Run Trainer
        env:
          OSM_COOKIES: ${{ secrets.OSM_COOKIES }}
          GREEN_API_INSTANCE: ${{ secrets.GREEN_API_INSTANCE }}
          GREEN_API_TOKEN: ${{ secrets.GREEN_API_TOKEN }}
          WHATSAPP_PHONE: ${{ secrets.WHATSAPP_PHONE }}
          TARGET_TEAM: ${{ secrets.TARGET_TEAM }}
          TARGET_LEAGUE: ${{ secrets.TARGET_LEAGUE }}
        run: xvfb-run --auto-servernum python -u trainer.py
